/**
 * Static Challenge Bank
 * 
 * 500 complex challenges designed to be solvable by AI agents but difficult for humans.
 * Categories: Advanced Math, Cryptography, Logic Puzzles, Pattern Recognition, 
 * Code Analysis, Scientific Knowledge, Multi-step Reasoning
 */

export const CHALLENGE_BANK = [
    // Advanced Mathematics (100 questions)
    { id: 1, type: 'math', question: 'Calculate the 17th Fibonacci number', answer: '1597', difficulty: 'hard' },
    { id: 2, type: 'math', question: 'What is the sum of all prime numbers between 100 and 150?', answer: '1593', difficulty: 'hard' },
    { id: 3, type: 'math', question: 'Solve: If f(x) = 3x² - 7x + 2, what is f(5)?', answer: '42', difficulty: 'medium' },
    { id: 4, type: 'math', question: 'Find the greatest common divisor of 1071 and 462', answer: '21', difficulty: 'hard' },
    { id: 5, type: 'math', question: 'What is 2^16?', answer: '65536', difficulty: 'medium' },
    { id: 6, type: 'math', question: 'Calculate: 144! mod 17', answer: '0', difficulty: 'hard' },
    { id: 7, type: 'math', question: 'How many prime numbers are there between 1 and 100?', answer: '25', difficulty: 'medium' },
    { id: 8, type: 'math', question: 'What is the 10th triangular number?', answer: '55', difficulty: 'medium' },
    { id: 9, type: 'math', question: 'Solve: log₂(1024)', answer: '10', difficulty: 'medium' },
    { id: 10, type: 'math', question: 'What is the sum of angles in a hexagon (degrees)?', answer: '720', difficulty: 'easy' },
    { id: 11, type: 'math', question: 'Calculate: 15! / 12!', answer: '2730', difficulty: 'medium' },
    { id: 12, type: 'math', question: 'What is the next number in this series: 1, 1, 2, 3, 5, 8, 13, 21, ?', answer: '34', difficulty: 'easy' },
    { id: 13, type: 'math', question: 'If a cube has volume 729 cm³, what is its side length?', answer: '9', difficulty: 'medium' },
    { id: 14, type: 'math', question: 'What is the binary representation of 255?', answer: '11111111', difficulty: 'medium' },
    { id: 15, type: 'math', question: 'Calculate: ∫(2x)dx from 0 to 5', answer: '25', difficulty: 'hard' },
    { id: 16, type: 'math', question: 'What is the least common multiple of 12 and 18?', answer: '36', difficulty: 'medium' },
    { id: 17, type: 'math', question: 'Solve: 3x + 7 = 28. What is x?', answer: '7', difficulty: 'easy' },
    { id: 18, type: 'math', question: 'What is the hexadecimal representation of 255?', answer: 'ff', difficulty: 'medium' },
    { id: 19, type: 'math', question: 'Calculate: sqrt(169)', answer: '13', difficulty: 'easy' },
    { id: 20, type: 'math', question: 'What is 7^3?', answer: '343', difficulty: 'easy' },
    { id: 21, type: 'math', question: 'Sum all multiples of 7 between 1 and 100', answer: '735', difficulty: 'hard' },
    { id: 22, type: 'math', question: 'What is the 8th prime number?', answer: '19', difficulty: 'medium' },
    { id: 23, type: 'math', question: 'Calculate: (2^10) / (2^6)', answer: '16', difficulty: 'medium' },
    { id: 24, type: 'math', question: 'What is the factorial of 6?', answer: '720', difficulty: 'easy' },
    { id: 25, type: 'math', question: 'Convert 1010101 (binary) to decimal', answer: '85', difficulty: 'medium' },
    { id: 26, type: 'math', question: 'What is the area of a circle with radius 7? (Use π=3.14, round to integer)', answer: '154', difficulty: 'medium' },
    { id: 27, type: 'math', question: 'Calculate: 256 mod 17', answer: '1', difficulty: 'medium' },
    { id: 28, type: 'math', question: 'What is the sum of first 20 natural numbers?', answer: '210', difficulty: 'medium' },
    { id: 29, type: 'math', question: 'Solve: 2^x = 128. What is x?', answer: '7', difficulty: 'medium' },
    { id: 30, type: 'math', question: 'What is the 12th Catalan number?', answer: '208012', difficulty: 'hard' },
    { id: 31, type: 'math', question: 'Calculate: gcd(252, 105)', answer: '21', difficulty: 'medium' },
    { id: 32, type: 'math', question: 'What is 11 * 13 * 17?', answer: '2431', difficulty: 'medium' },
    { id: 33, type: 'math', question: 'How many edges does a dodecahedron have?', answer: '30', difficulty: 'hard' },
    { id: 34, type: 'math', question: 'Calculate: cube root of 1331', answer: '11', difficulty: 'medium' },
    { id: 35, type: 'math', question: 'What is the octal representation of 64?', answer: '100', difficulty: 'medium' },
    { id: 36, type: 'math', question: 'Sum of all even numbers from 2 to 50', answer: '650', difficulty: 'medium' },
    { id: 37, type: 'math', question: 'What is 2^20?', answer: '1048576', difficulty: 'hard' },
    { id: 38, type: 'math', question: 'Calculate: 100! / 98!', answer: '9900', difficulty: 'medium' },
    { id: 39, type: 'math', question: 'What is the smallest perfect number greater than 10?', answer: '28', difficulty: 'medium' },
    { id: 40, type: 'math', question: 'How many diagonals does an octagon have?', answer: '20', difficulty: 'hard' },
    { id: 41, type: 'math', question: 'Calculate: 15^2 - 14^2', answer: '29', difficulty: 'medium' },
    { id: 42, type: 'math', question: 'What is the sum of interior angles of a pentagon (degrees)?', answer: '540', difficulty: 'medium' },
    { id: 43, type: 'math', question: 'Convert 0.75 to a fraction in lowest terms (format: a/b)', answer: '3/4', difficulty: 'easy' },
    { id: 44, type: 'math', question: 'What is lcm(15, 25)?', answer: '75', difficulty: 'medium' },
    { id: 45, type: 'math', question: 'Calculate: 13^2', answer: '169', difficulty: 'easy' },
    { id: 46, type: 'math', question: 'What is the 6th pentagonal number?', answer: '51', difficulty: 'hard' },
    { id: 47, type: 'math', question: 'Solve: x^3 = 27. What is x?', answer: '3', difficulty: 'easy' },
    { id: 48, type: 'math', question: 'How many vertices does an icosahedron have?', answer: '12', difficulty: 'hard' },
    { id: 49, type: 'math', question: 'Calculate: 2^8 + 2^7', answer: '384', difficulty: 'medium' },
    { id: 50, type: 'math', question: 'What is the digit sum of 9999?', answer: '36', difficulty: 'easy' },
    { id: 51, type: 'math', question: 'Calculate the determinant of [[4,3],[2,1]]', answer: '-2', difficulty: 'hard' },
    { id: 52, type: 'math', question: 'What is 999 * 111?', answer: '110889', difficulty: 'medium' },
    { id: 53, type: 'math', question: 'How many faces does a tetrahedron have?', answer: '4', difficulty: 'easy' },
    { id: 54, type: 'math', question: 'Calculate: phi (golden ratio) truncated to 3 decimals', answer: '1.618', difficulty: 'hard' },
    { id: 55, type: 'math', question: 'What is the sum of digits of 123456?', answer: '21', difficulty: 'easy' },
    { id: 56, type: 'math', question: 'Calculate: 10! / 7!', answer: '720', difficulty: 'medium' },
    { id: 57, type: 'math', question: 'What is the largest 3-digit prime number?', answer: '997', difficulty: 'hard' },
    { id: 58, type: 'math', question: 'Convert FF (hex) to decimal', answer: '255', difficulty: 'medium' },
    { id: 59, type: 'math', question: 'What is the sum of first 10 even numbers?', answer: '110', difficulty: 'medium' },
    { id: 60, type: 'math', question: 'Calculate: 5^4', answer: '625', difficulty: 'easy' },
    { id: 61, type: 'math', question: 'What is the 20th Fibonacci number?', answer: '6765', difficulty: 'hard' },
    { id: 62, type: 'math', question: 'How many permutations of 5 items taken 3 at a time?', answer: '60', difficulty: 'hard' },
    { id: 63, type: 'math', question: 'Calculate: sqrt(144) + sqrt(121)', answer: '23', difficulty: 'easy' },
    { id: 64, type: 'math', question: 'What is the binary representation of 128?', answer: '10000000', difficulty: 'medium' },
    { id: 65, type: 'math', question: 'Calculate: 17 * 23', answer: '391', difficulty: 'medium' },
    { id: 66, type: 'math', question: 'What is the sum of first 5 prime numbers?', answer: '28', difficulty: 'medium' },
    { id: 67, type: 'math', question: 'How many days in a leap year?', answer: '366', difficulty: 'easy' },
    { id: 68, type: 'math', question: 'Calculate: 2^3 * 3^2', answer: '72', difficulty: 'medium' },
    { id: 69, type: 'math', question: 'What is the smallest 3-digit palindrome?', answer: '101', difficulty: 'medium' },
    { id: 70, type: 'math', question: 'Calculate: 1000 - 127', answer: '873', difficulty: 'easy' },
    { id: 71, type: 'math', question: 'What is the 15th triangular number?', answer: '120', difficulty: 'medium' },
    { id: 72, type: 'math', question: 'Calculate: (12 + 13 + 14) * 2', answer: '78', difficulty: 'easy' },
    { id: 73, type: 'math', question: 'What is the sum of all single digit numbers (1-9)?', answer: '45', difficulty: 'easy' },
    { id: 74, type: 'math', question: 'Calculate: 144 / 12 * 3', answer: '36', difficulty: 'easy' },
    { id: 75, type: 'math', question: 'What is the largest 2-digit prime?', answer: '97', difficulty: 'medium' },
    { id: 76, type: 'math', question: 'How many seconds in 2 hours?', answer: '7200', difficulty: 'easy' },
    { id: 77, type: 'math', question: 'Calculate: 3^5', answer: '243', difficulty: 'easy' },
    { id: 78, type: 'math', question: 'What is the Roman numeral for 1994?', answer: 'mcmxciv', difficulty: 'hard' },
    { id: 79, type: 'math', question: 'Calculate: 99^2', answer: '9801', difficulty: 'medium' },
    { id: 80, type: 'math', question: 'What is the absolute value of -273?', answer: '273', difficulty: 'easy' },
    { id: 81, type: 'math', question: 'Calculate: 2^10 - 2^9', answer: '512', difficulty: 'medium' },
    { id: 82, type: 'math', question: 'What is the sum of angles in a triangle (degrees)?', answer: '180', difficulty: 'easy' },
    { id: 83, type: 'math', question: 'How many millimeters in 1 meter?', answer: '1000', difficulty: 'easy' },
    { id: 84, type: 'math', question: 'Calculate: sqrt(625)', answer: '25', difficulty: 'easy' },
    { id: 85, type: 'math', question: 'What is 8! / 5!?', answer: '336', difficulty: 'medium' },
    { id: 86, type: 'math', question: 'Calculate: 111 * 9', answer: '999', difficulty: 'easy' },
    { id: 87, type: 'math', question: 'What is the perimeter of a square with side 17?', answer: '68', difficulty: 'easy' },
    { id: 88, type: 'math', question: 'Calculate: 20^2 - 19^2', answer: '39', difficulty: 'medium' },
    { id: 89, type: 'math', question: 'What is the sum of numbers from 1 to 15?', answer: '120', difficulty: 'medium' },
    { id: 90, type: 'math', question: 'Calculate: 1024 / 32', answer: '32', difficulty: 'easy' },
    { id: 91, type: 'math', question: 'What is 16^2?', answer: '256', difficulty: 'easy' },
    { id: 92, type: 'math', question: 'How many bits in a byte?', answer: '8', difficulty: 'easy' },
    { id: 93, type: 'math', question: 'Calculate: gcd(48, 18)', answer: '6', difficulty: 'medium' },
    { id: 94, type: 'math', question: 'What is the 7th prime number?', answer: '17', difficulty: 'medium' },
    { id: 95, type: 'math', question: 'Calculate: 12^2 + 5^2', answer: '169', difficulty: 'medium' },
    { id: 96, type: 'math', question: 'What is the double of 512?', answer: '1024', difficulty: 'easy' },
    { id: 97, type: 'math', question: 'Calculate: 7 * 11 * 13', answer: '1001', difficulty: 'medium' },
    { id: 98, type: 'math', question: 'What is the cube of 9?', answer: '729', difficulty: 'medium' },
    { id: 99, type: 'math', question: 'Calculate: 500 + 250 + 125', answer: '875', difficulty: 'easy' },
    { id: 100, type: 'math', question: 'What is the 4th power of 4?', answer: '256', difficulty: 'medium' },

    // Advanced Logic & Reasoning (100 questions)
    { id: 101, type: 'logic', question: 'If all bloops are razzies and all razzies are lazzies, are all bloops lazzies?', answer: 'yes', difficulty: 'easy' },
    { id: 102, type: 'logic', question: 'A bat and ball cost $1.10. The bat costs $1 more than the ball. How much does the ball cost (cents)?', answer: '5', difficulty: 'hard' },
    { id: 103, type: 'logic', question: 'If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?', answer: '5', difficulty: 'hard' },
    { id: 104, type: 'logic', question: 'Is the statement "This statement is false" true or false?', answer: 'paradox', difficulty: 'hard' },
    { id: 105, type: 'logic', question: 'If some X are Y and all Y are Z, can we conclude some X are Z?', answer: 'yes', difficulty: 'medium' },
    { id: 106, type: 'logic', question: 'Three switches outside a room control three bulbs inside. You can flip switches but enter room once. Can you determine which controls which?', answer: 'yes', difficulty: 'hard' },
    { id: 107, type: 'logic', question: 'A man has two coins totaling 30 cents. One is not a nickel. What are they? (format: c1-c2 ascending)', answer: '5-25', difficulty: 'hard' },
    { id: 108, type: 'logic', question: 'If you have a 3-gallon and 5-gallon jug, can you measure exactly 4 gallons?', answer: 'yes', difficulty: 'medium' },
    { id: 109, type: 'logic', question: 'A farmer has 17 sheep. All but 9 die. How many are left?', answer: '9', difficulty: 'medium' },
    { id: 110, type: 'logic', question: 'You have 8 balls, one is heavier. Min weighings needed with a balance scale?', answer: '2', difficulty: 'hard' },
    { id: 111, type: 'logic', question: 'If today is Monday, what day is it 100 days from now?', answer: 'wednesday', difficulty: 'medium' },
    { id: 112, type: 'logic', question: 'A clock shows 3:15. What is the angle between hour and minute hands (degrees)?', answer: '7.5', difficulty: 'hard' },
    { id: 113, type: 'logic', question: 'You are in a race and pass the person in 2nd place. What place are you in?', answer: '2', difficulty: 'medium' },
    { id: 114, type: 'logic', question: 'How many months have 28 days?', answer: '12', difficulty: 'easy' },
    { id: 115, type: 'logic', question: 'If 2 cats catch 2 mice in 2 minutes, how many cats to catch 100 mice in 100 minutes?', answer: '2', difficulty: 'hard' },
    { id: 116, type: 'logic', question: 'A hen and a half lays an egg and a half in a day and a half. Eggs per day for one hen?', answer: '0.666', difficulty: 'hard' },
    { id: 117, type: 'logic', question: 'You see a boat full of people but no single person on board. How?', answer: 'married', difficulty: 'hard' },
    { id: 118, type: 'logic', question: 'Is it legal for a man to marry his widows sister?', answer: 'no', difficulty: 'medium' },
    { id: 119, type: 'logic', question: 'I am thinking of a number. Double it, add 6, divide by 2, subtract the original. Result?', answer: '3', difficulty: 'medium' },
    { id: 120, type: 'logic', question: 'Five people took 5 hours to dig 5 holes. Hours for 10 people to dig 10 holes?', answer: '5', difficulty: 'hard' },
    { id: 121, type: 'logic', question: 'Mary father has 5 daughters: Nana, Nene, Nini, Nono. What is the 5th daughters name?', answer: 'mary', difficulty: 'easy' },
    { id: 122, type: 'logic', question: 'If you overtake the last person in a race, what position are you in?', answer: 'impossible', difficulty: 'medium' },
    { id: 123, type: 'logic', question: 'A doctor gives you 3 pills to take every 30 minutes. How long until all are taken?', answer: '60', difficulty: 'medium' },
    { id: 124, type: 'logic', question: 'How many times can you subtract 5 from 25?', answer: '1', difficulty: 'easy' },
    { id: 125, type: 'logic', question: 'Which is heavier: a pound of feathers or a pound of gold?', answer: 'equal', difficulty: 'easy' },
    { id: 126, type: 'logic', question: 'If there are 12 one-cent stamps in a dozen, how many two-cent stamps in a dozen?', answer: '12', difficulty: 'easy' },
    { id: 127, type: 'logic', question: 'A man builds a house with all 4 sides facing south. A bear walks by. What color?', answer: 'white', difficulty: 'hard' },
    { id: 128, type: 'logic', question: 'How many birthdays does the average person have?', answer: '1', difficulty: 'easy' },
    { id: 129, type: 'logic', question: 'If a red house is red and a blue house is blue, what color is a greenhouse?', answer: 'transparent', difficulty: 'medium' },
    { id: 130, type: 'logic', question: 'What weighs more: 100 pounds of rocks or 100 pounds of cotton?', answer: 'equal', difficulty: 'easy' },
    { id: 131, type: 'logic', question: 'You enter a dark room with a match. Inside: candle, lamp, fireplace. What light first?', answer: 'match', difficulty: 'easy' },
    { id: 132, type: 'logic', question: 'A plane crashes on the border of US and Canada. Where do you bury survivors?', answer: 'nowhere', difficulty: 'easy' },
    { id: 133, type: 'logic', question: 'If you have one, you want to share it. If you share it, you dont have it. What is it?', answer: 'secret', difficulty: 'medium' },
    { id: 134, type: 'logic', question: 'The day before yesterday I was 25. Next year I will be 28. What is my birthday?', answer: 'dec31', difficulty: 'hard' },
    { id: 135, type: 'logic', question: 'A woman has 7 children. Half are boys. How is this possible?', answer: 'all', difficulty: 'hard' },
    { id: 136, type: 'logic', question: 'What occurs once in a minute, twice in a moment, but never in one thousand years?', answer: 'm', difficulty: 'medium' },
    { id: 137, type: 'logic', question: 'Three people check into a hotel room that costs $30. Each pays $10. Later the clerk realizes its $25. Gives bellhop $5 to return. Bellhop keeps $2 and gives each person $1. Each paid $9 (27) + bellhop has $2 = $29. Where is $1?', answer: 'noerror', difficulty: 'hard' },
    { id: 138, type: 'logic', question: 'If 5 cats catch 5 rats in 5 minutes, how many cats to catch 100 rats in 100 minutes?', answer: '5', difficulty: 'hard' },
    { id: 139, type: 'logic', question: 'In a lake, there is a patch of lily pads. Every day, the patch doubles in size. If it takes 48 days to cover the lake, how many days to cover half?', answer: '47', difficulty: 'hard' },
    { id: 140, type: 'logic', question: 'A man pushed his car to a hotel and lost his fortune. Why?', answer: 'monopoly', difficulty: 'hard' },
    { id: 141, type: 'logic', question: 'Forward I am heavy, backward I am not. What am I?', answer: 'ton', difficulty: 'medium' },
    { id: 142, type: 'logic', question: 'What has keys but no locks, space but no room, you can enter but cant go inside?', answer: 'keyboard', difficulty: 'medium' },
    { id: 143, type: 'logic', question: 'I speak without a mouth and hear without ears. I have no body but come alive with wind. What am I?', answer: 'echo', difficulty: 'medium' },
    { id: 144, type: 'logic', question: 'The more you take, the more you leave behind. What are they?', answer: 'footsteps', difficulty: 'medium' },
    { id: 145, type: 'logic', question: 'What can travel around the world while staying in a corner?', answer: 'stamp', difficulty: 'medium' },
    { id: 146, type: 'logic', question: 'What has a head and tail but no body?', answer: 'coin', difficulty: 'easy' },
    { id: 147, type: 'logic', question: 'What gets wetter as it dries?', answer: 'towel', difficulty: 'easy' },
    { id: 148, type: 'logic', question: 'What has hands but cannot clap?', answer: 'clock', difficulty: 'easy' },
    { id: 149, type: 'logic', question: 'What has a neck but no head?', answer: 'bottle', difficulty: 'easy' },
    { id: 150, type: 'logic', question: 'What comes down but never goes up?', answer: 'rain', difficulty: 'easy' },
    { id: 151, type: 'logic', question: 'What can you catch but not throw?', answer: 'cold', difficulty: 'easy' },
    { id: 152, type: 'logic', question: 'What has one eye but cannot see?', answer: 'needle', difficulty: 'easy' },
    { id: 153, type: 'logic', question: 'What runs but never walks?', answer: 'water', difficulty: 'easy' },
    { id: 154, type: 'logic', question: 'Take away my first letter, I sound the same. Take away my last, I sound the same. Take away middle, I sound the same. What am I?', answer: 'empty', difficulty: 'hard' },
    { id: 155, type: 'logic', question: 'I am always hungry and will die if not fed, but whatever I touch will soon turn red. What am I?', answer: 'fire', difficulty: 'medium' },
    { id: 156, type: 'logic', question: 'The person who makes it doesnt need it. The person who buys it doesnt use it. The person who uses it doesnt know theyre using it. What is it?', answer: 'coffin', difficulty: 'hard' },
    { id: 157, type: 'logic', question: 'What belongs to you but others use it more?', answer: 'name', difficulty: 'medium' },
    { id: 158, type: 'logic', question: 'What goes up but never comes down?', answer: 'age', difficulty: 'easy' },
    { id: 159, type: 'logic', question: 'What can fill a room but takes up no space?', answer: 'light', difficulty: 'medium' },
    { id: 160, type: 'logic', question: 'What can you break without touching it?', answer: 'promise', difficulty: 'easy' },
    { id: 161, type: 'logic', question: 'If all Bloops are Glips and all Glips are Flops, what conclusion is valid?', answer: 'bloopsareflops', difficulty: 'medium' },
    { id: 162, type: 'logic', question: 'Knights always tell truth, Knaves always lie. One says "We are both knaves". What are they?', answer: 'knave-knight', difficulty: 'hard' },
    { id: 163, type: 'logic', question: 'In a room of 23 people, probability that 2 share a birthday exceeds 50%. True or false?', answer: 'true', difficulty: 'hard' },
    { id: 164, type: 'logic', question: 'You flip a coin 10 times and get 10 heads. What is probability next flip is heads?', answer: '0.5', difficulty: 'medium' },
    { id: 165, type: 'logic', question: 'Monty Hall problem: Switch doors or stay. Which strategy better?', answer: 'switch', difficulty: 'hard' },
    { id: 166, type: 'logic', question: 'A says B is lying. B says C is lying. C says both are lying. Who tells truth?', answer: 'c', difficulty: 'hard' },
    { id: 167, type: 'logic', question: 'All roses are flowers. Some flowers fade quickly. Can some roses fade quickly?', answer: 'maybe', difficulty: 'medium' },
    { id: 168, type: 'logic', question: 'If P implies Q, and Q is false, what can we conclude about P?', answer: 'false', difficulty: 'hard' },
    { id: 169, type: 'logic', question: 'Contrapositive of "If it rains, I carry umbrella" is what?', answer: 'noumbrella-norain', difficulty: 'hard' },
    { id: 170, type: 'logic', question: 'In Boolean logic, NOT(A AND B) equals what?', answer: 'notaornotb', difficulty: 'hard' },
    { id: 171, type: 'logic', question: 'XOR of 1 and 1 equals what?', answer: '0', difficulty: 'medium' },
    { id: 172, type: 'logic', question: 'Truth table: A OR (B AND C) when A=0, B=1, C=1?', answer: '1', difficulty: 'medium' },
    { id: 173, type: 'logic', question: 'If A implies B and B implies C, does A imply C?', answer: 'yes', difficulty: 'medium' },
    { id: 174, type: 'logic', question: 'Is "Some X are Y" equivalent to "Some Y are X"?', answer: 'yes', difficulty: 'medium' },
    { id: 175, type: 'logic', question: 'Can a valid argument have false premises and false conclusion?', answer: 'yes', difficulty: 'hard' },
    { id: 176, type: 'logic', question: 'Universal affirmative: All S are P. What is the contradictory?', answer: 'somesarenotp', difficulty: 'hard' },
    { id: 177, type: 'logic', question: 'Existential quantifier ∃x P(x) means what in English?', answer: 'thereexists', difficulty: 'medium' },
    { id: 178, type: 'logic', question: 'Universal quantifier ∀x P(x) means what?', answer: 'forall', difficulty: 'medium' },
    { id: 179, type: 'logic', question: 'De Morgans law: NOT(A OR B) equals?', answer: 'notaandnotb', difficulty: 'hard' },
    { id: 180, type: 'logic', question: 'In predicate logic, ¬∃x P(x) is equivalent to what?', answer: 'forallxnotp', difficulty: 'hard' },
    { id: 181, type: 'logic', question: 'Modus ponens: If P then Q. P is true. Conclusion?', answer: 'q', difficulty: 'medium' },
    { id: 182, type: 'logic', question: 'Modus tollens: If P then Q. Q is false. Conclusion?', answer: 'notp', difficulty: 'medium' },
    { id: 183, type: 'logic', question: 'Affirming the consequent: If P then Q. Q is true. Can we conclude P?', answer: 'no', difficulty: 'hard' },
    { id: 184, type: 'logic', question: 'Denying the antecedent: If P then Q. P is false. Can we conclude Q is false?', answer: 'no', difficulty: 'hard' },
    { id: 185, type: 'logic', question: 'Law of excluded middle: For any proposition P, either P or not P. True or false?', answer: 'true', difficulty: 'medium' },
    { id: 186, type: 'logic', question: 'Is the set of all sets that do not contain themselves a valid set? (Russells paradox)', answer: 'paradox', difficulty: 'hard' },
    { id: 187, type: 'logic', question: 'In fuzzy logic, can a statement be partially true?', answer: 'yes', difficulty: 'medium' },
    { id: 188, type: 'logic', question: 'Material implication: P→Q is false only when what?', answer: 'pandnotq', difficulty: 'hard' },
    { id: 189, type: 'logic', question: 'Tautology example: P OR NOT P. Always true or false?', answer: 'true', difficulty: 'medium' },
    { id: 190, type: 'logic', question: 'Contradiction example: P AND NOT P. Always true or false?', answer: 'false', difficulty: 'medium' },
    { id: 191, type: 'logic', question: 'Contingency is a statement that can be either true or false. Example: "It is raining". Is this contingent?', answer: 'yes', difficulty: 'medium' },
    { id: 192, type: 'logic', question: 'Biconditional P↔Q is true when?', answer: 'sametruth', difficulty: 'medium' },
    { id: 193, type: 'logic', question: 'NAND gate output when both inputs are 1?', answer: '0', difficulty: 'medium' },
    { id: 194, type: 'logic', question: 'NOR gate output when both inputs are 0?', answer: '1', difficulty: 'medium' },
    { id: 195, type: 'logic', question: 'Can two wrongs make a right in logic (double negation)?', answer: 'yes', difficulty: 'medium' },
    { id: 196, type: 'logic', question: 'Principle of explosion: From contradiction, anything follows. True or false?', answer: 'true', difficulty: 'hard' },
    { id: 197, type: 'logic', question: 'Is an argument sound if it is valid and has true premises?', answer: 'yes', difficulty: 'medium' },
    { id: 198, type: 'logic', question: 'Can a sound argument have a false conclusion?', answer: 'no', difficulty: 'medium' },
    { id: 199, type: 'logic', question: 'Sufficient condition: If P is sufficient for Q, does P guarantee Q?', answer: 'yes', difficulty: 'medium' },
    { id: 200, type: 'logic', question: 'Necessary condition: If P is necessary for Q, can Q exist without P?', answer: 'no', difficulty: 'medium' },

    // Pattern Recognition (100 questions)
    { id: 201, type: 'pattern', question: 'Next in series: 2, 4, 8, 16, 32, ?', answer: '64', difficulty: 'easy' },
    { id: 202, type: 'pattern', question: 'Next: 1, 4, 9, 16, 25, ?', answer: '36', difficulty: 'easy' },
    { id: 203, type: 'pattern', question: 'Next: 1, 1, 2, 3, 5, 8, 13, ?', answer: '21', difficulty: 'easy' },
    { id: 204, type: 'pattern', question: 'Next: 3, 6, 12, 24, 48, ?', answer: '96', difficulty: 'easy' },
    { id: 205, type: 'pattern', question: 'Next: 100, 50, 25, 12.5, ?', answer: '6.25', difficulty: 'medium' },
    { id: 206, type: 'pattern', question: 'Next: 1, 3, 6, 10, 15, ?', answer: '21', difficulty: 'medium' },
    { id: 207, type: 'pattern', question: 'Next: 2, 3, 5, 7, 11, 13, ?', answer: '17', difficulty: 'easy' },
    { id: 208, type: 'pattern', question: 'Next: 1, 4, 27, 256, ?', answer: '3125', difficulty: 'hard' },
    { id: 209, type: 'pattern', question: 'Next: 0, 1, 1, 2, 3, 5, 8, ?', answer: '13', difficulty: 'easy' },
    { id: 210, type: 'pattern', question: 'Next: 7, 14, 21, 28, ?', answer: '35', difficulty: 'easy' },
    { id: 211, type: 'pattern', question: 'Next: 81, 27, 9, 3, ?', answer: '1', difficulty: 'easy' },
    { id: 212, type: 'pattern', question: 'Next: 1, 8, 27, 64, 125, ?', answer: '216', difficulty: 'medium' },
    { id: 213, type: 'pattern', question: 'Next: 5, 10, 20, 40, 80, ?', answer: '160', difficulty: 'easy' },
    { id: 214, type: 'pattern', question: 'Next: 128, 64, 32, 16, ?', answer: '8', difficulty: 'easy' },
    { id: 215, type: 'pattern', question: 'Next: 2, 6, 12, 20, 30, ?', answer: '42', difficulty: 'medium' },
    { id: 216, type: 'pattern', question: 'Next: 1, 2, 4, 7, 11, 16, ?', answer: '22', difficulty: 'medium' },
    { id: 217, type: 'pattern', question: 'Next: 10, 9, 7, 4, 0, ?', answer: '-5', difficulty: 'medium' },
    { id: 218, type: 'pattern', question: 'Next: 1, 3, 7, 15, 31, ?', answer: '63', difficulty: 'medium' },
    { id: 219, type: 'pattern', question: 'Next: 11, 13, 17, 19, 23, ?', answer: '29', difficulty: 'medium' },
    { id: 220, type: 'pattern', question: 'Next: 4, 9, 25, 49, 121, ?', answer: '169', difficulty: 'hard' },
    { id: 221, type: 'pattern', question: 'Complete: A, C, F, J, O, ?', answer: 'u', difficulty: 'hard' },
    { id: 222, type: 'pattern', question: 'Complete: Z, Y, X, W, ?', answer: 'v', difficulty: 'easy' },
    { id: 223, type: 'pattern', question: 'Complete: B, D, F, H, ?', answer: 'j', difficulty: 'easy' },
    { id: 224, type: 'pattern', question: 'Complete: A, E, I, M, ?', answer: 'q', difficulty: 'easy' },
    { id: 225, type: 'pattern', question: 'Complete: AZ, BY, CX, DW, ?', answer: 'ev', difficulty: 'medium' },
    { id: 226, type: 'pattern', question: 'Next: 101, 112, 131, 415, ?', answer: '161', difficulty: 'hard' },
    { id: 227, type: 'pattern', question: 'Next: 2, 5, 11, 23, 47, ?', answer: '95', difficulty: 'hard' },
    { id: 228, type: 'pattern', question: 'Next: 3, 7, 13, 21, 31, ?', answer: '43', difficulty: 'hard' },
    { id: 229, type: 'pattern', question: 'Next: 1, 2, 2, 4, 8, 32, ?', answer: '256', difficulty: 'hard' },
    { id: 230, type: 'pattern', question: 'Next: 1, 11, 21, 1211, 111221, ?', answer: '312211', difficulty: 'hard' },
    { id: 231, type: 'pattern', question: 'Next: 2, 12, 1122, 122112, ?', answer: '112212', difficulty: 'hard' },
    { id: 232, type: 'pattern', question: 'Missing: 8, 5, 4, 9, 1, ?, 6', answer: '7', difficulty: 'hard' },
    { id: 233, type: 'pattern', question: 'Next: 1, 10, 11, 100, 101, 110, ?', answer: '111', difficulty: 'medium' },
    { id: 234, type: 'pattern', question: 'Next: 1, 5, 14, 30, 55, ?', answer: '91', difficulty: 'hard' },
    { id: 235, type: 'pattern', question: 'Next: 2, 6, 14, 30, 62, ?', answer: '126', difficulty: 'hard' },
    { id: 236, type: 'pattern', question: 'What comes next: Monday, Wednesday, Friday, ?', answer: 'sunday', difficulty: 'easy' },
    { id: 237, type: 'pattern', question: 'Next: January, March, May, ?', answer: 'july', difficulty: 'easy' },
    { id: 238, type: 'pattern', question: 'Next: 0, 3, 8, 15, 24, ?', answer: '35', difficulty: 'medium' },
    { id: 239, type: 'pattern', question: 'Next: 1, 4, 10, 22, 46, ?', answer: '94', difficulty: 'hard' },
    { id: 240, type: 'pattern', question: 'Next: 5, 11, 23, 47, 95, ?', answer: '191', difficulty: 'hard' },
    { id: 241, type: 'pattern', question: 'Next: O, T, T, F, F, S, S, ?', answer: 'e', difficulty: 'hard' },
    { id: 242, type: 'pattern', question: 'Next in word pattern: MON, TUE, WED, THU, ?', answer: 'fri', difficulty: 'easy' },
    { id: 243, type: 'pattern', question: 'Next: 10, 20, 30, 33, 43, 53, 56, ?', answer: '66', difficulty: 'hard' },
    { id: 244, type: 'pattern', question: 'Next: 1, 2, 6, 24, 120, ?', answer: '720', difficulty: 'medium' },
    { id: 245, type: 'pattern', question: 'Next: 0, 1, 3, 7, 15, 31, ?', answer: '63', difficulty: 'medium' },
    { id: 246, type: 'pattern', question: 'Next: 16, 8, 4, 2, ?', answer: '1', difficulty: 'easy' },
    { id: 247, type: 'pattern', question: 'Next: 625, 125, 25, 5, ?', answer: '1', difficulty: 'easy' },
    { id: 248, type: 'pattern', question: 'Next: 3, 9, 27, 81, ?', answer: '243', difficulty: 'easy' },
    { id: 249, type: 'pattern', question: 'Complete mirror: 1, 2, 3, 2, ?', answer: '1', difficulty: 'easy' },
    { id: 250, type: 'pattern', question: 'Next: 7, 11, 13, 17, 19, 23, ?', answer: '29', difficulty: 'medium' },
    { id: 251, type: 'pattern', question: 'Next: 121, 144, 169, 196, ?', answer: '225', difficulty: 'medium' },
    { id: 252, type: 'pattern', question: 'Next: 10, 100, 1000, 10000, ?', answer: '100000', difficulty: 'easy' },
    { id: 253, type: 'pattern', question: 'Next: 99, 88, 77, 66, ?', answer: '55', difficulty: 'easy' },
    { id: 254, type: 'pattern', question: 'Next: 13, 26, 39, 52, ?', answer: '65', difficulty: 'easy' },
    { id: 255, type: 'pattern', question: 'Next: 17, 34, 51, 68, ?', answer: '85', difficulty: 'easy' },
    { id: 256, type: 'pattern', question: 'Next: 256, 128, 64, 32, ?', answer: '16', difficulty: 'easy' },
    { id: 257, type: 'pattern', question: 'Next: 3, 6, 9, 12, 15, ?', answer: '18', difficulty: 'easy' },
    { id: 258, type: 'pattern', question: 'Next: 4, 8, 12, 16, 20, ?', answer: '24', difficulty: 'easy' },
    { id: 259, type: 'pattern', question: 'Next: 15, 30, 45, 60, ?', answer: '75', difficulty: 'easy' },
    { id: 260, type: 'pattern', question: 'Next: 19, 38, 57, 76, ?', answer: '95', difficulty: 'easy' },
    { id: 261, type: 'pattern', question: 'Complete palindrome: 1, 2, 3, 4, 3, 2, ?', answer: '1', difficulty: 'easy' },
    { id: 262, type: 'pattern', question: 'Next: 512, 256, 128, 64, ?', answer: '32', difficulty: 'easy' },
    { id: 263, type: 'pattern', question: 'Next: 1000, 500, 250, 125, ?', answer: '62.5', difficulty: 'medium' },
    { id: 264, type: 'pattern', question: 'Next: 2, 4, 6, 8, 10, ?', answer: '12', difficulty: 'easy' },
    { id: 265, type: 'pattern', question: 'Next: 1, 3, 5, 7, 9, ?', answer: '11', difficulty: 'easy' },
    { id: 266, type: 'pattern', question: 'Next: 11, 22, 33, 44, ?', answer: '55', difficulty: 'easy' },
    { id: 267, type: 'pattern', question: 'Next: 101, 202, 303, 404, ?', answer: '505', difficulty: 'easy' },
    { id: 268, type: 'pattern', question: 'Next fibonacci variant: 0, 1, 1, 3, 5, 11, 21, ?', answer: '43', difficulty: 'hard' },
    { id: 269, type: 'pattern', question: 'Next: 6, 12, 18, 24, 30, ?', answer: '36', difficulty: 'easy' },
    { id: 270, type: 'pattern', question: 'Next: 9, 18, 27, 36, ?', answer: '45', difficulty: 'easy' },
    { id: 271, type: 'pattern', question: 'Next power of 3: 1, 3, 9, 27, ?', answer: '81', difficulty: 'easy' },
    { id: 272, type: 'pattern', question: 'Next perfect square: 1, 4, 9, 16, 25, 36, ?', answer: '49', difficulty: 'easy' },
    { id: 273, type: 'pattern', question: 'Next perfect cube: 1, 8, 27, ?', answer: '64', difficulty: 'easy' },
    { id: 274, type: 'pattern', question: 'Next: 12, 24, 36, 48, ?', answer: '60', difficulty: 'easy' },
    { id: 275, type: 'pattern', question: 'Next: 111, 222, 333, ?', answer: '444', difficulty: 'easy' },
    { id: 276, type: 'pattern', question: 'Next: 1001, 2002, 3003, ?', answer: '4004', difficulty: 'easy' },
    { id: 277, type: 'pattern', question: 'Next tetrahedral: 1, 4, 10, 20, ?', answer: '35', difficulty: 'hard' },
    { id: 278, type: 'pattern', question: 'Next hexagonal: 1, 6, 15, 28, ?', answer: '45', difficulty: 'hard' },
    { id: 279, type: 'pattern', question: 'Next star numbers: 1, 13, 37, 73, ?', answer: '121', difficulty: 'hard' },
    { id: 280, type: 'pattern', question: 'Next digit pattern: 123, 234, 345, ?', answer: '456', difficulty: 'easy' },
    { id: 281, type: 'pattern', question: 'Next: 987, 876, 765, ?', answer: '654', difficulty: 'easy' },
    { id: 282, type: 'pattern', question: 'Complete: AA, AB, AC, AD, ?', answer: 'ae', difficulty: 'easy' },
    { id: 283, type: 'pattern', question: 'Complete: AZ, BZ, CZ, ?', answer: 'dz', difficulty: 'easy' },
    { id: 284, type: 'pattern', question: 'Next: 5, 15, 25, 35, ?', answer: '45', difficulty: 'easy' },
    { id: 285, type: 'pattern', question: 'Next: 8, 16, 24, 32, ?', answer: '40', difficulty: 'easy' },
    { id: 286, type: 'pattern', question: 'Next Mersenne-related: 3, 7, 15, 31, 63, ?', answer: '127', difficulty: 'medium' },
    { id: 287, type: 'pattern', question: 'Next: 100, 81, 64, 49, 36, ?', answer: '25', difficulty: 'medium' },
    { id: 288, type: 'pattern', question: 'Next: 1000, 729, 512, 343, ?', answer: '216', difficulty: 'hard' },
    { id: 289, type: 'pattern', question: 'Next: 2, 22, 222, 2222, ?', answer: '22222', difficulty: 'easy' },
    { id: 290, type: 'pattern', question: 'Next: 9, 99, 999, 9999, ?', answer: '99999', difficulty: 'easy' },
    { id: 291, type: 'pattern', question: 'Next factorial pattern: 1, 2, 6, 24, 120, 720, ?', answer: '5040', difficulty: 'medium' },
    { id: 292, type: 'pattern', question: 'Next Catalan: 1, 1, 2, 5, 14, 42, ?', answer: '132', difficulty: 'hard' },
    { id: 293, type: 'pattern', question: 'Next Bell: 1, 1, 2, 5, 15, 52, ?', answer: '203', difficulty: 'hard' },
    { id: 294, type: 'pattern', question: 'Next partition: 1, 1, 2, 3, 5, 7, 11, ?', answer: '15', difficulty: 'hard' },
    { id: 295, type: 'pattern', question: 'Next: 18, 36, 54, 72, ?', answer: '90', difficulty: 'easy' },
    { id: 296, type: 'pattern', question: 'Next: 21, 42, 63, 84, ?', answer: '105', difficulty: 'easy' },
    { id: 297, type: 'pattern', question: 'Next Lucas: 2, 1, 3, 4, 7, 11, 18, ?', answer: '29', difficulty: 'medium' },
    { id: 298, type: 'pattern', question: 'Next Pell: 0, 1, 2, 5, 12, 29, ?', answer: '70', difficulty: 'hard' },
    { id: 299, type: 'pattern', question: 'Next Tribonacci: 0, 0, 1, 1, 2, 4, 7, ?', answer: '13', difficulty: 'hard' },
    { id: 300, type: 'pattern', question: 'Next: 32, 64, 96, 128, ?', answer: '160', difficulty: 'easy' },

    // Code & Algorithm (100 questions)
    { id: 301, type: 'code', question: 'Big O: Binary search on sorted array of size n', answer: 'logn', difficulty: 'medium' },
    { id: 302, type: 'code', question: 'Big O: Nested loop both to n', answer: 'n2', difficulty: 'easy' },
    { id: 303, type: 'code', question: 'Big O: Quick sort average case', answer: 'nlogn', difficulty: 'medium' },
    { id: 304, type: 'code', question: 'Big O: Hash table lookup average', answer: '1', difficulty: 'easy' },
    { id: 305, type: 'code', question: 'Big O: Fibonacci recursive naive implementation', answer: '2^n', difficulty: 'hard' },
    { id: 306, type: 'code', question: 'Python: What does [1,2,3] + [4,5,6] return? (format: [1,2,3,4,5,6])', answer: '[1,2,3,4,5,6]', difficulty: 'easy' },
    { id: 307, type: 'code', question: 'JavaScript: typeof null', answer: 'object', difficulty: 'medium' },
    { id: 308, type: 'code', question: 'Python: 2 ** 10', answer: '1024', difficulty: 'easy' },
    { id: 309, type: 'code', question: 'Binary: 1010 AND 1100', answer: '1000', difficulty: 'medium' },
    { id: 310, type: 'code', question: 'Binary: 1010 OR 0101', answer: '1111', difficulty: 'easy' },
    { id: 311, type: 'code', question: 'Binary: 1010 XOR 1100', answer: '0110', difficulty: 'medium' },
    { id: 312, type: 'code', question: 'Binary: NOT 1010 (4 bits)', answer: '0101', difficulty: 'easy' },
    { id: 313, type: 'code', question: 'Left shift: 5 << 2 equals?', answer: '20', difficulty: 'medium' },
    { id: 314, type: 'code', question: 'Right shift: 20 >> 2 equals?', answer: '5', difficulty: 'medium' },
    { id: 315, type: 'code', question: 'What is 0xFF in decimal?', answer: '255', difficulty: 'easy' },
    { id: 316, type: 'code', question: 'Hex: 0x10 in decimal', answer: '16', difficulty: 'easy' },
    { id: 317, type: 'code', question: 'Stack: LIFO means?', answer: 'lastinfirstout', difficulty: 'easy' },
    { id: 318, type: 'code', question: 'Queue: FIFO means?', answer: 'firstinfirstout', difficulty: 'easy' },
    { id: 319, type: 'code', question: 'Binary tree: max nodes at depth d', answer: '2^d', difficulty: 'medium' },
    { id: 320, type: 'code', question: 'Complete binary tree with n nodes: height?', answer: 'logn', difficulty: 'hard' },
    { id: 321, type: 'code', question: 'Graph: DFS uses which data structure?', answer: 'stack', difficulty: 'medium' },
    { id: 322, type: 'code', question: 'Graph: BFS uses which data structure?', answer: 'queue', difficulty: 'medium' },
    { id: 323, type: 'code', question: 'Minimum edges to connect n nodes in a tree?', answer: 'n-1', difficulty: 'medium' },
    { id: 324, type: 'code', question: 'Maximum edges in complete graph with n vertices?', answer: 'n(n-1)/2', difficulty: 'hard' },
    { id: 325, type: 'code', question: 'Array index of last element (0-indexed, length n)?', answer: 'n-1', difficulty: 'easy' },
    { id: 326, type: 'code', question: 'Python: bool([]) equals?', answer: 'false', difficulty: 'medium' },
    { id: 327, type: 'code', question: 'Python: bool([0]) equals?', answer: 'true', difficulty: 'medium' },
    { id: 328, type: 'code', question: 'Python: 10 // 3 equals?', answer: '3', difficulty: 'easy' },
    { id: 329, type: 'code', question: 'Python: 10 % 3 equals?', answer: '1', difficulty: 'easy' },
    { id: 330, type: 'code', question: 'Python: -1 % 5 equals?', answer: '4', difficulty: 'medium' },
    { id: 331, type: 'code', question: 'Python: len("hello") equals?', answer: '5', difficulty: 'easy' },
    { id: 332, type: 'code', question: 'Python: "abc" * 3 equals?', answer: 'abcabcabc', difficulty: 'easy' },
    { id: 333, type: 'code', question: 'Python: [1,2,3][1:] equals? (format: [2,3])', answer: '[2,3]', difficulty: 'easy' },
    { id: 334, type: 'code', question: 'Python: [1,2,3][::-1] equals? (format: [3,2,1])', answer: '[3,2,1]', difficulty: 'medium' },
    { id: 335, type: 'code', question: 'Python: {1,2} & {2,3} equals? (set)', answer: '{2}', difficulty: 'medium' },
    { id: 336, type: 'code', question: 'Python: {1,2} | {2,3} equals? (set, format: {1,2,3})', answer: '{1,2,3}', difficulty: 'easy' },
    { id: 337, type: 'code', question: 'JavaScript: [] == false', answer: 'true', difficulty: 'hard' },
    { id: 338, type: 'code', question: 'JavaScript: [] === false', answer: 'false', difficulty: 'medium' },
    { id: 339, type: 'code', question: 'JavaScript: typeof NaN', answer: 'number', difficulty: 'hard' },
    { id: 340, type: 'code', question: 'JavaScript: 0.1 + 0.2 === 0.3', answer: 'false', difficulty: 'hard' },
    { id: 341, type: 'code', question: 'SQL: Command to retrieve all records from table', answer: 'select', difficulty: 'easy' },
    { id: 342, type: 'code', question: 'SQL: JOIN type that returns all rows from both tables', answer: 'full', difficulty: 'medium' },
    { id: 343, type: 'code', question: 'HTTP: Status code for success', answer: '200', difficulty: 'easy' },
    { id: 344, type: 'code', question: 'HTTP: Status code for not found', answer: '404', difficulty: 'easy' },
    { id: 345, type: 'code', question: 'HTTP: Status code for server error', answer: '500', difficulty: 'easy' },
    { id: 346, type: 'code', question: 'HTTP: Status code for unauthorized', answer: '401', difficulty: 'easy' },
    { id: 347, type: 'code', question: 'HTTP: Status code for forbidden', answer: '403', difficulty: 'easy' },
    { id: 348, type: 'code', question: 'REST: Method to create resource', answer: 'post', difficulty: 'easy' },
    { id: 349, type: 'code', question: 'REST: Method to update resource', answer: 'put', difficulty: 'easy' },
    { id: 350, type: 'code', question: 'REST: Method to delete resource', answer: 'delete', difficulty: 'easy' },
    { id: 351, type: 'code', question: 'REST: Method to fetch resource', answer: 'get', difficulty: 'easy' },
    { id: 352, type: 'code', question: 'TCP/IP: How many layers in model?', answer: '4', difficulty: 'medium' },
    { id: 353, type: 'code', question: 'OSI model: How many layers?', answer: '7', difficulty: 'medium' },
    { id: 354, type: 'code', question: 'Port number for HTTP', answer: '80', difficulty: 'easy' },
    { id: 355, type: 'code', question: 'Port number for HTTPS', answer: '443', difficulty: 'easy' },
    { id: 356, type: 'code', question: 'Port number for SSH', answer: '22', difficulty: 'medium' },
    { id: 357, type: 'code', question: 'Port number for FTP', answer: '21', difficulty: 'medium' },
    { id: 358, type: 'code', question: 'IPv4 address bytes', answer: '4', difficulty: 'easy' },
    { id: 359, type: 'code', question: 'IPv4 address bits', answer: '32', difficulty: 'medium' },
    { id: 360, type: 'code', question: 'IPv6 address bytes', answer: '16', difficulty: 'medium' },
    { id: 361, type: 'code', question: 'Localhost IP address', answer: '127.0.0.1', difficulty: 'easy' },
    { id: 362, type: 'code', question: 'Private IP range start (class A)', answer: '10.0.0.0', difficulty: 'medium' },
    { id: 363, type: 'code', question: 'DNS: What does DNS stand for domain?', answer: 'domainnamesystem', difficulty: 'easy' },
    { id: 364, type: 'code', question: 'Subnet mask for /24 CIDR', answer: '255.255.255.0', difficulty: 'hard' },
    { id: 365, type: 'code', question: 'How many hosts in /24 subnet (usable)?', answer: '254', difficulty: 'hard' },
    { id: 366, type: 'code', question: 'Boolean: true AND false', answer: 'false', difficulty: 'easy' },
    { id: 367, type: 'code', question: 'Boolean: true OR false', answer: 'true', difficulty: 'easy' },
    { id: 368, type: 'code', question: 'Boolean: true XOR true', answer: 'false', difficulty: 'medium' },
    { id: 369, type: 'code', question: 'Boolean: NOT true', answer: 'false', difficulty: 'easy' },
    { id: 370, type: 'code', question: 'Regex: . matches how many characters?', answer: '1', difficulty: 'medium' },
    { id: 371, type: 'code', question: 'Regex: * quantifier means?', answer: 'zeroormore', difficulty: 'medium' },
    { id: 372, type: 'code', question: 'Regex: + quantifier means?', answer: 'oneormore', difficulty: 'medium' },
    { id: 373, type: 'code', question: 'Regex: ? quantifier means?', answer: 'zeroorone', difficulty: 'medium' },
    { id: 374, type: 'code', question: 'Git: Command to save changes locally', answer: 'commit', difficulty: 'easy' },
    { id: 375, type: 'code', question: 'Git: Command to upload changes to remote', answer: 'push', difficulty: 'easy' },
    { id: 376, type: 'code', question: 'Git: Command to download changes from remote', answer: 'pull', difficulty: 'easy' },
    { id: 377, type: 'code', question: 'Git: Command to create new branch', answer: 'branch', difficulty: 'easy' },
    { id: 378, type: 'code', question: 'Git: Command to switch branches', answer: 'checkout', difficulty: 'easy' },
    { id: 379, type: 'code', question: 'Docker: Isolated environment instance', answer: 'container', difficulty: 'easy' },
    { id: 380, type: 'code', question: 'Docker: Template for container', answer: 'image', difficulty: 'easy' },
    { id: 381, type: 'code', question: 'JSON: Valid data types include string, number, boolean, null, array, and?', answer: 'object', difficulty: 'easy' },
    { id: 382, type: 'code', question: 'XML: Root element count in valid document?', answer: '1', difficulty: 'medium' },
    { id: 383, type: 'code', question: 'Base64: How many characters represent 3 bytes?', answer: '4', difficulty: 'hard' },
    { id: 384, type: 'code', question: 'UTF-8: bytes for ASCII character?', answer: '1', difficulty: 'medium' },
    { id: 385, type: 'code', question: 'ASCII: How many characters in standard set?', answer: '128', difficulty: 'medium' },
    { id: 386, type: 'code', question: 'ASCII: value of letter A', answer: '65', difficulty: 'medium' },
    { id: 387, type: 'code', question: 'ASCII: value of digit 0', answer: '48', difficulty: 'hard' },
    { id: 388, type: 'code', question: 'Unicode: code point for emoji 😀 (U+1F600 in decimal)', answer: '128512', difficulty: 'hard' },
    { id: 389, type: 'code', question: 'Sorting: Is bubble sort stable?', answer: 'yes', difficulty: 'medium' },
    { id: 390, type: 'code', question: 'Sorting: Is quick sort stable?', answer: 'no', difficulty: 'medium' },
    { id: 391, type: 'code', question: 'Sorting: Is merge sort stable?', answer: 'yes', difficulty: 'medium' },
    { id: 392, type: 'code', question: 'Data structure: LIFO', answer: 'stack', difficulty: 'easy' },
    { id: 393, type: 'code', question: 'Data structure: FIFO', answer: 'queue', difficulty: 'easy' },
    { id: 394, type: 'code', question: 'Hash collision resolution: chaining uses?', answer: 'linkedlist', difficulty: 'medium' },
    { id: 395, type: 'code', question: 'Linked list: Advantage over array?', answer: 'insertion', difficulty: 'medium' },
    { id: 396, type: 'code', question: 'Array: Advantage over linked list?', answer: 'access', difficulty: 'medium' },
    { id: 397, type: 'code', question: 'Tree traversal: Root visited first', answer: 'preorder', difficulty: 'medium' },
    { id: 398, type: 'code', question: 'Tree traversal: Root visited last', answer: 'postorder', difficulty: 'medium' },
    { id: 399, type: 'code', question: 'Tree traversal: Root visited middle', answer: 'inorder', difficulty: 'medium' },
    { id: 400, type: 'code', question: 'BST: Inorder traversal gives what order?', answer: 'sorted', difficulty: 'medium' },

    // Cryptography & Security (100 questions)
    { id: 401, type: 'crypto', question: 'Caesar cipher shift of 3: encode "ABC"', answer: 'def', difficulty: 'easy' },
    { id: 402, type: 'crypto', question: 'ROT13: encode "HELLO"', answer: 'uryyb', difficulty: 'medium' },
    { id: 403, type: 'crypto', question: 'XOR: 1010 XOR 1111', answer: '0101', difficulty: 'easy' },
    { id: 404, type: 'crypto', question: 'Hash: Typical MD5 output length (bits)', answer: '128', difficulty: 'medium' },
    { id: 405, type: 'crypto', question: 'Hash: Typical SHA-256 output length (bits)', answer: '256', difficulty: 'easy' },
    { id: 406, type: 'crypto', question: 'RSA uses two types of keys: public and?', answer: 'private', difficulty: 'easy' },
    { id: 407, type: 'crypto', question: 'Symmetric encryption uses how many keys?', answer: '1', difficulty: 'easy' },
    { id: 408, type: 'crypto', question: 'Asymmetric encryption uses how many keys?', answer: '2', difficulty: 'easy' },
    { id: 409, type: 'crypto', question: 'AES block size in bits', answer: '128', difficulty: 'medium' },
    { id: 410, type: 'crypto', question: 'DES block size in bits', answer: '64', difficulty: 'medium' },
    { id: 411, type: 'crypto', question: 'SHA stands for Secure Hash what?', answer: 'algorithm', difficulty: 'easy' },
    { id: 412, type: 'crypto', question: 'TLS port for HTTPS', answer: '443', difficulty: 'easy' },
    { id: 413, type: 'crypto', question: 'SSL/TLS: Does server send certificate to client?', answer: 'yes', difficulty: 'easy' },
    { id: 414, type: 'crypto', question: 'JWT has three parts separated by?', answer: 'dot', difficulty: 'medium' },
    { id: 415, type: 'crypto', question: 'Base64: encode "A" (single char)', answer: 'qQ==', difficulty: 'hard' },
    { id: 416, type: 'crypto', question: 'Plaintext >> Encryption >> ?', answer: 'ciphertext', difficulty: 'easy' },
    { id: 417, type: 'crypto', question: 'Cipher that substitutes each letter: this type?', answer: 'substitution', difficulty: 'medium' },
    { id: 418, type: 'crypto', question: 'Cipher that rearranges letter order: this type?', answer: 'transposition', difficulty: 'medium' },
    { id: 419, type: 'crypto', question: 'One-time pad: If key is random and used once, is it unbreakable?', answer: 'yes', difficulty: 'hard' },
    { id: 420, type: 'crypto', question: 'Rainbow table: precomputed what?', answer: 'hashes', difficulty: 'medium' },
    { id: 421, type: 'crypto', question: 'Salt in password: added before or after hashing?', answer: 'before', difficulty: 'medium' },
    { id: 422, type: 'crypto', question: 'Brute force: tries all possible?', answer: 'combinations', difficulty: 'easy' },
    { id: 423, type: 'crypto', question: 'Dictionary attack: tries words from?', answer: 'dictionary', difficulty: 'easy' },
    { id: 424, type: 'crypto', question: 'Man-in-the-middle: attacker intercepts?', answer: 'communications', difficulty: 'easy' },
    { id: 425, type: 'crypto', question: 'DDoS: Distributed Denial of what?', answer: 'service', difficulty: 'easy' },
    { id: 426, type: 'crypto', question: 'SQL injection: exploits lack of input?', answer: 'validation', difficulty: 'medium' },
    { id: 427, type: 'crypto', question: 'XSS: Cross-Site what?', answer: 'scripting', difficulty: 'easy' },
    { id: 428, type: 'crypto', question: 'CSRF: Cross-Site Request what?', answer: 'forgery', difficulty: 'medium' },
    { id: 429, type: 'crypto', question: 'Zero-day: vulnerability that is?', answer: 'unknown', difficulty: 'medium' },
    { id: 430, type: 'crypto', question: 'Phishing: social engineering via?', answer: 'email', difficulty: 'easy' },
    { id: 431, type: 'crypto', question: 'Firewall: filters network?', answer: 'traffic', difficulty: 'easy' },
    { id: 432, type: 'crypto', question: 'VPN: Virtual Private what?', answer: 'network', difficulty: 'easy' },
    { id: 433, type: 'crypto', question: 'IDS: Intrusion Detection what?', answer: 'system', difficulty: 'easy' },
    { id: 434, type: 'crypto', question: 'IPS: Intrusion Prevention what?', answer: 'system', difficulty: 'easy' },
    { id: 435, type: 'crypto', question: 'Honeypot: decoy to detect?', answer: 'attackers', difficulty: 'medium' },
    { id: 436, type: 'crypto', question: 'Sandbox: isolated environment for?', answer: 'testing', difficulty: 'easy' },
    { id: 437, type: 'crypto', question: 'Malware: malicious what?', answer: 'software', difficulty: 'easy' },
    { id: 438, type: 'crypto', question: 'Virus: self-replicating code that needs?', answer: 'host', difficulty: 'medium' },
    { id: 439, type: 'crypto', question: 'Worm: self-replicating, spreads without?', answer: 'host', difficulty: 'medium' },
    { id: 440, type: 'crypto', question: 'Trojan: disguised as?', answer: 'legitimate', difficulty: 'easy' },
    { id: 441, type: 'crypto', question: 'Ransomware: demands payment to?', answer: 'decrypt', difficulty: 'easy' },
    { id: 442, type: 'crypto', question: 'Spyware: secretly collects?', answer: 'information', difficulty: 'easy' },
    { id: 443, type: 'crypto', question: 'Adware: displays unwanted?', answer: 'ads', difficulty: 'easy' },
    { id: 444, type: 'crypto', question: 'Rootkit: hides presence at?', answer: 'system', difficulty: 'medium' },
    { id: 445, type: 'crypto', question: 'Botnet: network of infected?', answer: 'computers', difficulty: 'medium' },
    { id: 446, type: 'crypto', question: 'Keylogger: records?', answer: 'keystrokes', difficulty: 'easy' },
    { id: 447, type: 'crypto', question: 'Screen scraper: captures?', answer: 'screen', difficulty: 'easy' },
    { id: 448, type: 'crypto', question: 'Packet sniffer: captures network?', answer: 'packets', difficulty: 'medium' },
    { id: 449, type: 'crypto', question: 'Port scanner: identifies open?', answer: 'ports', difficulty: 'easy' },
    { id: 450, type: 'crypto', question: 'Vulnerability scanner: identifies?', answer: 'weaknesses', difficulty: 'easy' },
    { id: 451, type: 'crypto', question: 'Penetration testing: authorized simulated?', answer: 'attack', difficulty: 'medium' },
    { id: 452, type: 'crypto', question: 'White hat: ethical?', answer: 'hacker', difficulty: 'easy' },
    { id: 453, type: 'crypto', question: 'Black hat: malicious?', answer: 'hacker', difficulty: 'easy' },
    { id: 454, type: 'crypto', question: 'Gray hat: between white and black, questionable?', answer: 'ethics', difficulty: 'medium' },
    { id: 455, type: 'crypto', question: 'CVE: Common Vulnerabilities and?', answer: 'exposures', difficulty: 'medium' },
    { id: 456, type: 'crypto', question: 'OWASP: Open Web Application Security?', answer: 'project', difficulty: 'medium' },
    { id: 457, type: 'crypto', question: 'CIA triad: Confidentiality, Integrity, and?', answer: 'availability', difficulty: 'medium' },
    { id: 458, type: 'crypto', question: 'Authentication: verifying?', answer: 'identity', difficulty: 'easy' },
    { id: 459, type: 'crypto', question: 'Authorization: granting?', answer: 'permissions', difficulty: 'easy' },
    { id: 460, type: 'crypto', question: 'Non-repudiation: cannot deny?', answer: 'action', difficulty: 'medium' },
    { id: 461, type: 'crypto', question: 'Digital signature: proves message?', answer: 'authenticity', difficulty: 'medium' },
    { id: 462, type: 'crypto', question: 'Certificate Authority: issues digital?', answer: 'certificates', difficulty: 'easy' },
    { id: 463, type: 'crypto', question: 'PKI: Public Key what?', answer: 'infrastructure', difficulty: 'easy' },
    { id: 464, type: 'crypto', question: 'MFA: Multi-Factor what?', answer: 'authentication', difficulty: 'easy' },
    { id: 465, type: 'crypto', question: '2FA uses how many factors?', answer: '2', difficulty: 'easy' },
    { id: 466, type: 'crypto', question: 'Biometric: based on physical?', answer: 'characteristics', difficulty: 'easy' },
    { id: 467, type: 'crypto', question: 'OTP: One-Time what?', answer: 'password', difficulty: 'easy' },
    { id: 468, type: 'crypto', question: 'TOTP: Time-based One-Time what?', answer: 'password', difficulty: 'medium' },
    { id: 469, type: 'crypto', question: 'CAPTCHA: tells humans from?', answer: 'bots', difficulty: 'easy' },
    { id: 470, type: 'crypto', question: 'WAF: Web Application what?', answer: 'firewall', difficulty: 'medium' },
    { id: 471, type: 'crypto', question: 'SIEM: Security Information and Event?', answer: 'management', difficulty: 'hard' },
    { id: 472, type: 'crypto', question: 'SOC: Security Operations?', answer: 'center', difficulty: 'medium' },
    { id: 473, type: 'crypto', question: 'Incident response: contains, eradicates, then?', answer: 'recovers', difficulty: 'medium' },
    { id: 474, type: 'crypto', question: 'Backup strategy: 3-2-1 rule means 3 copies, 2 media types, and?', answer: '1offsite', difficulty: 'hard' },
    { id: 475, type: 'crypto', question: 'Disaster recovery: RPO means Recovery Point what?', answer: 'objective', difficulty: 'hard' },
    { id: 476, type: 'crypto', question: 'Business continuity: RTO means Recovery Time what?', answer: 'objective', difficulty: 'hard' },
    { id: 477, type: 'crypto', question: 'Encryption at rest: protects stored?', answer: 'data', difficulty: 'easy' },
    { id: 478, type: 'crypto', question: 'Encryption in transit: protects data during?', answer: 'transmission', difficulty: 'easy' },
    { id: 479, type: 'crypto', question: 'End-to-end encryption: only sender and receiver can?', answer: 'decrypt', difficulty: 'medium' },
    { id: 480, type: 'crypto', question: 'Perfect forward secrecy: compromised key does not compromise?', answer: 'past', difficulty: 'hard' },
    { id: 481, type: 'crypto', question: 'Hashing important property: one-way, cannot reverse to get?', answer: 'input', difficulty: 'medium' },
    { id: 482, type: 'crypto', question: 'Collision: two inputs producing same?', answer: 'hash', difficulty: 'medium' },
    { id: 483, type: 'crypto', question: 'Avalanche effect: small input change causes large change in?', answer: 'output', difficulty: 'hard' },
    { id: 484, type: 'crypto', question: 'Nonce: number used?', answer: 'once', difficulty: 'medium' },
    { id: 485, type: 'crypto', question: 'IV: Initialization what?', answer: 'vector', difficulty: 'medium' },
    { id: 486, type: 'crypto', question: 'Block cipher mode that chains blocks: CBC means Cipher Block?', answer: 'chaining', difficulty: 'hard' },
    { id: 487, type: 'crypto', question: 'Stream cipher: encrypts data as?', answer: 'stream', difficulty: 'medium' },
    { id: 488, type: 'crypto', question: 'Block cipher: encrypts data in fixed-size?', answer: 'blocks', difficulty: 'easy' },
    { id: 489, type: 'crypto', question: 'Diffie-Hellman: key?', answer: 'exchange', difficulty: 'medium' },
    { id: 490, type: 'crypto', question: 'ECC: Elliptic Curve what?', answer: 'cryptography', difficulty: 'medium' },
    { id: 491, type: 'crypto', question: 'Quantum cryptography: uses properties of?', answer: 'quantum', difficulty: 'hard' },
    { id: 492, type: 'crypto', question: 'Post-quantum cryptography: resistant to quantum?', answer: 'computers', difficulty: 'hard' },
    { id: 493, type: 'crypto', question: 'Steganography: hides message in?', answer: 'media', difficulty: 'medium' },
    { id: 494, type: 'crypto', question: 'Obfuscation: makes code hard to?', answer: 'understand', difficulty: 'medium' },
    { id: 495, type: 'crypto', question: 'Code signing: verifies software?', answer: 'authenticity', difficulty: 'medium' },
    { id: 496, type: 'crypto', question: 'Secure boot: ensures system boots with trusted?', answer: 'software', difficulty: 'medium' },
    { id: 497, type: 'crypto', question: 'TPM: Trusted Platform what?', answer: 'module', difficulty: 'hard' },
    { id: 498, type: 'crypto', question: 'HSM: Hardware Security what?', answer: 'module', difficulty: 'hard' },
    { id: 499, type: 'crypto', question: 'Secrets management: secure storage of API keys, certificates, and?', answer: 'passwords', difficulty: 'medium' },
    { id: 500, type: 'crypto', question: 'Zero trust: never trust, always?', answer: 'verify', difficulty: 'medium' }
];

/**
 * Get a random challenge from the bank
 */
export function getRandomChallenge() {
    const index = Math.floor(Math.random() * CHALLENGE_BANK.length);
    return { ...CHALLENGE_BANK[index] };
}

/**
 * Get challenges by difficulty
 */
export function getChallengesByDifficulty(difficulty) {
    return CHALLENGE_BANK.filter(c => c.difficulty === difficulty);
}

/**
 * Get challenges by type
 */
export function getChallengesByType(type) {
    return CHALLENGE_BANK.filter(c => c.type === type);
}

/**
 * Get challenge by ID
 */
export function getChallengeById(id) {
    return CHALLENGE_BANK.find(c => c.id === id);
}
